repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run python -m mypy .
        language: system
        require_serial: true
        pass_filenames: false
        types_or: [python, pyi]
