# Generated by Django 3.2.7 on 2022-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_add_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperuserOnlyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
            ],
        ),
    ]
